# coding: utf-8

"""
    SCORM Cloud Rest API

    REST API used for SCORM Cloud integrations.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: systems@rusticisoftware.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConnectorContentItemSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'updated': 'datetime',
        'metadata': 'MetadataSchema'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'updated': 'updated',
        'metadata': 'metadata'
    }

    def __init__(self, id=None, title=None, updated=None, metadata=None):  # noqa: E501
        """ConnectorContentItemSchema - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._updated = None
        self._metadata = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if updated is not None:
            self.updated = updated
        if metadata is not None:
            self.metadata = metadata

    @property
    def id(self):
        """Gets the id of this ConnectorContentItemSchema.  # noqa: E501


        :return: The id of this ConnectorContentItemSchema.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConnectorContentItemSchema.


        :param id: The id of this ConnectorContentItemSchema.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this ConnectorContentItemSchema.  # noqa: E501


        :return: The title of this ConnectorContentItemSchema.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ConnectorContentItemSchema.


        :param title: The title of this ConnectorContentItemSchema.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def updated(self):
        """Gets the updated of this ConnectorContentItemSchema.  # noqa: E501


        :return: The updated of this ConnectorContentItemSchema.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this ConnectorContentItemSchema.


        :param updated: The updated of this ConnectorContentItemSchema.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def metadata(self):
        """Gets the metadata of this ConnectorContentItemSchema.  # noqa: E501


        :return: The metadata of this ConnectorContentItemSchema.  # noqa: E501
        :rtype: MetadataSchema
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ConnectorContentItemSchema.


        :param metadata: The metadata of this ConnectorContentItemSchema.  # noqa: E501
        :type: MetadataSchema
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectorContentItemSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectorContentItemSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
