# coding: utf-8

"""
    SCORM Cloud Rest API

    REST API used for SCORM Cloud integrations.

    OpenAPI spec version: 2.0
    Contact: systems@rusticisoftware.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DispatchRegistrationCountSchema(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, registration_count=None, last_reset_date=None):
        """
        DispatchRegistrationCountSchema - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'registration_count': 'int',
            'last_reset_date': 'datetime'
        }

        self.attribute_map = {
            'registration_count': 'registrationCount',
            'last_reset_date': 'lastResetDate'
        }

        self._registration_count = registration_count
        self._last_reset_date = last_reset_date

    @property
    def registration_count(self):
        """
        Gets the registration_count of this DispatchRegistrationCountSchema.

        :return: The registration_count of this DispatchRegistrationCountSchema.
        :rtype: int
        """
        return self._registration_count

    @registration_count.setter
    def registration_count(self, registration_count):
        """
        Sets the registration_count of this DispatchRegistrationCountSchema.

        :param registration_count: The registration_count of this DispatchRegistrationCountSchema.
        :type: int
        """

        self._registration_count = registration_count

    @property
    def last_reset_date(self):
        """
        Gets the last_reset_date of this DispatchRegistrationCountSchema.

        :return: The last_reset_date of this DispatchRegistrationCountSchema.
        :rtype: datetime
        """
        return self._last_reset_date

    @last_reset_date.setter
    def last_reset_date(self, last_reset_date):
        """
        Sets the last_reset_date of this DispatchRegistrationCountSchema.

        :param last_reset_date: The last_reset_date of this DispatchRegistrationCountSchema.
        :type: datetime
        """

        self._last_reset_date = last_reset_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DispatchRegistrationCountSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
