# coding: utf-8

"""
    SCORM Cloud Rest API

    REST API used for SCORM Cloud integrations.  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: systems@rusticisoftware.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class XapiCredentialAuthTypeSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'xapi_credential_auth_type': 'str'
    }

    attribute_map = {
        'xapi_credential_auth_type': 'xapiCredentialAuthType'
    }

    def __init__(self, xapi_credential_auth_type=None):  # noqa: E501
        """XapiCredentialAuthTypeSchema - a model defined in Swagger"""  # noqa: E501

        self._xapi_credential_auth_type = None
        self.discriminator = None

        if xapi_credential_auth_type is not None:
            self.xapi_credential_auth_type = xapi_credential_auth_type

    @property
    def xapi_credential_auth_type(self):
        """Gets the xapi_credential_auth_type of this XapiCredentialAuthTypeSchema.  # noqa: E501


        :return: The xapi_credential_auth_type of this XapiCredentialAuthTypeSchema.  # noqa: E501
        :rtype: str
        """
        return self._xapi_credential_auth_type

    @xapi_credential_auth_type.setter
    def xapi_credential_auth_type(self, xapi_credential_auth_type):
        """Sets the xapi_credential_auth_type of this XapiCredentialAuthTypeSchema.


        :param xapi_credential_auth_type: The xapi_credential_auth_type of this XapiCredentialAuthTypeSchema.  # noqa: E501
        :type: str
        """
        allowed_values = ["BASICAUTH", "OAUTH"]  # noqa: E501
        if xapi_credential_auth_type not in allowed_values:
            raise ValueError(
                "Invalid value for `xapi_credential_auth_type` ({0}), must be one of {1}"  # noqa: E501
                .format(xapi_credential_auth_type, allowed_values)
            )

        self._xapi_credential_auth_type = xapi_credential_auth_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(XapiCredentialAuthTypeSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XapiCredentialAuthTypeSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
